Swfupload/Controllers/ExifController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.IO;
using System.Windows.Media;
using System.Windows.Media.Imaging;

using Swfupload.Models;

namespace Swfupload.Controllers
{
    public class ExifController : Controller
    {
        //
        // GET: /Exif/

        [RedirectFilter(Controller="Home", Action="About")]
        public ActionResult Index()
        {
            return View();
        }

        //
        // POST: /Exif/Read

        [HttpPost]
        public ActionResult Read(HttpPostedFileBase fileUpload)
        {
            FileUploadResult result = new FileUploadResult();
            result.FileName = fileUpload.FileName;

            BitmapMetadata sourceMetadata = null;
            BitmapCreateOptions createOptions = BitmapCreateOptions.PreservePixelFormat | BitmapCreateOptions.IgnoreColorProfile;

            using (Stream stream = fileUpload.InputStream)
            {
                BitmapDecoder sourceDecoder = BitmapDecoder.Create(stream, createOptions, BitmapCacheOption.None);
                if (sourceDecoder.Frames[0] != null && sourceDecoder.Frames[0].Metadata != null)
                {
                    sourceMetadata = sourceDecoder.Frames[0].Metadata.Clone() as BitmapMetadata;
                }
            }

            // due to the way file submission + AJAX works we cannot return a JSON object
            // instead we must return a json-like string
            // return Json(new { foo = "bar" });  // browsers don't quite handle this correctly
            return Content(result.ToJSON(), "text/html");
        }

    }
}

Swfupload/Views/Exif/Index.cshtml
@{
    ViewBag.Title = "EXIF Data";
}

@section Head {
<script src="@Url.Content("~/Scripts/Exif/exif.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jQuery.Form/jquery.form.js")" type="text/javascript"></script>
<style type="text/css">
    .main { border:1px solid #ccc; }
    .flow { display:table-cell; padding:5px; }
    #upload-container { border: 1px solid #ccc; }
    #exif-container { border: 1px solid #ccc; vertical-align:top; }
    .upload-fieldset { border: 1px solid #c5dbec; margin: 5px; padding: 3px; display: inline-block; }
    .field-div { padding:2px 0 3px 5px; }
    legend { font-family:Lucida Grande, Lucida Sans, Arial, sans-serif; color:#2e6e9e; }
    .exif-label { font-weight:bold; padding:0 5px 0 0; display:table-cell; }
    .exif-data { display:table-cell; }
</style>
}

<h2>EXIF Data</h2>

<div class="main">
    <div id="upload-container" class="flow">
        <form id="upload" action="@Url.Action("Read", "Exif")" method="post" enctype="multipart/form-data">
            <fieldset class="upload-fieldset">
                <legend>Upload</legend>
                <div class="field-div"><input id="fileUpload" name="fileUpload" type="file" multiple="multiple" /></div>
                <div class="field-div"><button id="submit-btn" type="submit">Submit</button></div>
            </fieldset>
        </form>
    </div>

    <div id="exif-container" class="flow">
        <div><div class="exif-label">Date</div><div class="exif-data">2/1/2010</div></div>
        <div><div class="exif-label">ISO</div><div class="exif-data">200</div></div>
    </div>
</div>